### ISSUE TITLE
Do we have a way to create `object` and `struct` with classic R functions?

### ISSUE THREAD

**Issue by etiennebacher** [pola-rs/r-polars#1012]
I don't think we have a way to create `object` and `struct` from our standard `c()` and `list()` but maybe I'm missing something?

It would be good to have a small table in the docs to show the equivalent (if any) of those:

```python
pl.Series(values=[1])
shape: (1,)
Series: '' [i64]
[
        1
]

> pl$Series(values = 1)
polars Series: shape: (1,)
Series: '' [f64]
[
	1.0
]
```

```python
>>> pl.Series(values=[[1]])
shape: (1,)
Series: '' [list[i64]]
[
        [1]
]

> pl$Series(values = list(1))
polars Series: shape: (1,)
Series: '' [list[f64]]
[
	[1.0]
]
```

```python
>>> pl.Series(values=[{1}])
shape: (1,)
Series: '' [o][object]
[
        {1}
]

???
```

```python
>>> pl.Series(values=[{"a": 1}])
shape: (1,)
Series: '' [struct[1]]
[
        {1}
]

???
```

**Comment by eitsupi** [comment]
Are you looking for `pl$Series(values = data.frame(a = 1))`?

**Comment by eitsupi** [comment]
IIUC, the object type is Python-specific, not the Apatch Arrow type.

**Comment by etiennebacher** [comment]
> Are you looking for `pl$Series(values = data.frame(a = 1))`?

This is equivalent to calling a list:

> pl$Series(values = data.frame(a = 1))
polars Series: shape: (1,)
Series: '' [list[f64]]
[
	[1.0]
]
> pl$Series(values = list(a = 1))
polars Series: shape: (1,)
Series: '' [list[f64]]
[
	[1.0]
]

**Comment by eitsupi** [comment]
Oh, sorry. This is the one.
https://github.com/pola-rs/r-polars/blob/main/R%2Fas_polars.R#L367-L371

**Comment by eitsupi** [comment]
Can we close this now that #1015 has been merged?
As I commented, the Object type is for storing Python objects, so I don't see the point in supporting it here.
(Since R's list can contain a variety of things, we can always use the base R data.frame if we want to store something that is not supported by Apache Arrow)

**Comment by etiennebacher** [comment]
>  As I commented, the Object type is for storing Python objects, so I don't see the point in supporting it here.

That's something worth mentioning in the docs I think. I'll add that in #1014 and close this issue with this PR

**Comment by etiennebacher** [comment]
Actually it's hard to construct `Struct` for `Series`:
```python
>>> pl.Series([{"a": 1, "b": ["x", "y"]}, {"a": 2, "b": ["z"]}])
shape: (2,)
Series: '' [struct[2]]
[
        {1,["x", "y"]}
        {2,["z"]}
]
```
```{r}
as_polars_series(
  data.frame(a = 1:2, b = list(c("x", "y"), "z"))
)

polars Series: shape: (2,)
Series: '' [struct[3]]
[
	{1,"x","z"}
	{2,"y","z"}
]
```
And it doesn't work for `DataFrame`:

```{r}
as_polars_df(
  data.frame(a = 1)
)

shape: (1, 1)
┌─────┐
│ a   │
│ --- │
│ f64 │
╞═════╡
│ 1.0 │
└─────┘
```

Maybe we should say that we can't reliably create a `Struct` from scratch and point towards `$to_struct()` instead

**Comment by eitsupi** [comment]
> Actually it's hard to construct `Struct` for `Series`:

I think nested types are something that base's data.frame cannot handle well. Use tibble instead.

``` r
polars::as_polars_series(
  data.frame(a = 1:2, b = list(c("x", "y"), "z"))
)
#> polars Series: shape: (2,)
#> Series: '' [struct[3]]
#> [
#>  {1,"x","z"}
#>  {2,"y","z"}
#> ]

polars::as_polars_series(
  tibble::tibble(a = 1:2, b = list(c("x", "y"), "z"))
)
#> polars Series: shape: (2,)
#> Series: '' [struct[2]]
#> [
#>  {1,["x", "y"]}
#>  {2,["z"]}
#> ]
```

<sup>Created on 2024-04-10 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

> And it doesn't work for `DataFrame`:

`pl$DataFrame()` works like `as_polars_df()` when it receives a data.frame.
(I think this behavior is worth removing because I find it confusing, but the point is that `data.frame()` works the same way, and in Python, `polars.DataFrame.__init__()` will convert a pandas.DataFrame to a polars.DataFame, so this is consistent behavior)

``` r
polars::pl$DataFrame(data.frame(a = 1))
#> shape: (1, 1)
#> ┌─────┐
#> │ a   │
#> │ --- │
#> │ f64 │
#> ╞═════╡
#> │ 1.0 │
#> └─────┘
polars::pl$DataFrame(a = data.frame(a = 1))
#> shape: (1, 1)
#> ┌───────────┐
#> │ a         │
#> │ ---       │
#> │ struct[1] │
#> ╞═══════════╡
#> │ {1.0}     │
#> └───────────┘
```

<sup>Created on 2024-04-10 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
