### ISSUE TITLE
Release 0.18.0

### ISSUE THREAD

**Issue by etiennebacher** [pola-rs/r-polars#1157]
@eitsupi in the end I'm not sure it's worth implementing the checks for empty dots now that the rewrite has started. I don't want to invest time on this if it turns out that the whole codebase will change in a few weeks.

Therefore, unless there are things you want to address in particular, I think we can release 0.18.0.

**Comment by eitsupi** [comment]
Thank you. However, the rewrite will take a few months (I was hoping to complete the work while Python Polars is in v1)

Well, in any case, we can release 0.18.0 and check the dots afterwards, and I will work on the release.

**Comment by etiennebacher** [comment]
Ok, I am hesitating on where I should put my focus now. There are new functions to implement from upstream but if I do it on `main` then they will have to be rewritten in the next weeks/months, so it seems like a waste of work. Do you think I should now focus more effort on the `next` branch?

**Comment by eitsupi** [comment]
This is a difficult decision because we cannot predict at this time when the switch to the `next` branch will be possible.

In my opinion, if the feature is very important and easy to implement (i.e., if most of it is handled upstream in Rust and only a small wrapper is needed here), then the changes in the current main branch are worthwhile.
I feel that more than half of the work to add the functionality added upstream to the R package as well would involve adding tests and documentation, which should be mostly copiable to the `next` branch.
On the other hand, if a feature is described by a large amount of Python code in Python Polars, it might be better to hold off on adding it to the `main` branch.

So I will continue to update the Rust Polars, and I think that the rest of the work should be minimal.
