### ISSUE TITLE
Translation questions

### ISSUE THREAD

**Issue by vincentarelbundock** [pola-rs/r-polars#119]
Sorry to ask so many questions, but I'm still trying to figure out how this all works.

#### Multi-type arguments

Some arguments accept multiple types. For example, `LazyFrame.shift_and_fill` has a `fill_value` argument which can be Expr, int, str, float: https://pola-rs.github.io/polars/py-polars/html/reference/lazyframe/api/polars.LazyFrame.shift_and_fill.html#polars-lazyframe-shift-and-fill

Something like this compiles:

```rust
pub fn shift_and_fill(&self, fill_value: Robj, periods: Robj) -> Result<Self, String> {
    Ok(self.clone().0.shift_and_fill(robj_to!(i64, fill_value)?, robj_to!(i64, periods)?).into())
}
```

How can I make `fill_value` accept different types? When I try to switch `i64` for something else I get an "expected `i64`" error.

#### `Expr` argument in `LazyFrame.quantile()`

The function compiles:

```rust
pub fn quantile(&self, quantile: &Expr, interpolation: &str) -> Result<LazyFrame, String> {
    let res = new_quantile_interpolation_option(interpolation).unwrap();
    Ok(LazyFrame(self.clone().0.quantile(quantile.0.clone(), res)))
}
```

```r
Error in .pr$LazyFrame$quantile(self, quantile, interpolation) : 
  expected Expr
```

How can I define `quantile: Robj` and then convert that argument into an appropriate `Expr` for the `.quantile` method?

#### `ChunkedArray`

Does R-polars support returning `ChunkedArray` objects, as in the `is_unique()` method? I tried various simple things without success

**Comment by sorhawell** [comment]
> Sorry to ask so many questions

Please ask away, I was pulling my hair for long when I started this project :)

In the end both py-polars and r-polars must interface with the rust [LazyFrame.html/method.shift_and_fill](LazyFrame.html#method.shift_and_fill)

```rust
  pub fn shift_and_fill<E: Into<Expr>>(self, periods: i64, fill_value: E) -> Self {
        self.select_local(vec![col("*").shift_and_fill(periods, fill_value.into())])
    }
  ```
So E is a generic type  Into<Expr>, which means `fill_value` could ideally be anything that implements the Trait "implicitly convertable into an `Expr`. [We used this trait in previous PR to achieve slightly more ergonomic code ](https://github.com/vincentarelbundock/r-polars/blob/512e8065b582a3f89ba284385c058d1ef9e77bf4/src/rust/src/lazy/dataframe.rs#L17). From and Into are two sides of the same coin. **Edit oh I see the source of confusion now, in rust function `periods` is first and the `fill_value` is last. In py-polars it is opposite. The generic flexibility of Into<Expr> allows `fill_value` to accept an `i64`**

...back to the too long explanation 😸 
Since rust is statically typed, when wrapping this method in py-polars or r-polars`fill_value` we must settle on a type. Since the `Expr` is an Enum(c++ enum + c++ union) under the hood, it can contain any `Expr` including literals which are e.g. Int and String wrapped in an Expr-enum. [The whole polars dsl expression lang is largely just the same enum `Expr](https://pola-rs.github.io/polars/src/polars_plan/dsl/expr.rs.html#310)` wrapping it self into a syntax tree at runtime. All the expression methods are just adding extra pieces to the syntax tree, one piece at the time.

looking at the py-polars rust wrapper in [polars](https://github.com/pola-rs/polars/tree/main)/[py-polars](https://github.com/pola-rs/polars/tree/main/py-polars)/[src](https://github.com/pola-rs/polars/tree/main/py-polars/src)/[lazy](https://github.com/pola-rs/polars/tree/main/py-polars/src/lazy)/dataframe.rs
```rust
pub fn shift_and_fill(&self, periods: i64, fill_value: PyExpr) -> Self {
        let ldf = self.ldf.clone();
        ldf.shift_and_fill(periods, fill_value.inner).into()
    }
```
fill_value is a  `PyExpr` which the thinnest possible wrapper around rust `Expr`-type. We have these wrapper types on any rust-type, because we can then get to redefine methods and associated traits as we like. To get the inner rust-type to pass it on, the inner field is here called inner and is unwrapped like `fill_value.inner`. In py-polars the inner of wrappers is not always called inner. E.g. the inner field of PyLazyFrame is called `ldf`. That is why the inner rust LazyFrame is acquired by calling `self.ldf.clone()`. In r-polars all wrappers are tupple-structs, and the inner field is always and only called 0.
Lastly after calling rust  `ldf.shift_and_fill(periods, fill_value.inner)` then `.into()` is added to convert back to the wrapper type which is converted back to python.

One source of confusion is that currently due to a limitation in Extendr (and my choice of class system), we have in r-polars to name the wrapper type same as the inner rust type. So rust Expr is wrapped by R wrapper named Expr also, and so on for most classes.

this should work better
```rust
fn shift_and_fill(&self, fill_value: Robj, periods: Robj) -> Result<Self, String> {
    Ok(self.clone().0.shift_and_fill(robj_to!(i64, periods)?,robj_to!(Expr, fill_value)?).into())
}
```

just for reference the most direct translation of py-polars would be like this
```rust
fn shift_and_fill(&self, fill_value: &Expr, periods: i64) -> Self {
    self.clone().0.shift_and_fill(periods, fill_value.0.clone()).into()
}
```

**Comment by sorhawell** [comment]
> How can I define quantile: Robj and then convert that argument into an appropriate Expr for the .quantile method?

Try check out [ExprStr_replace](https://github.com/pola-rs/r-polars/blob/e9d98de423f69a0f94c7b46504741cdc587b389c/R/expr__string.R#L652)

```R
#' @param pattern Into<Expr>, regex pattern
#' @param value Into<Expr> replcacement
ExprStr_replace = function(pattern, value, literal = FALSE){
  .pr$Expr$str_replace(self, wrap_e_result(pattern), wrap_e_result(value), result(literal)) |>
    unwrap("in str$replace:")
}
```

```rust
   pub fn str_replace(&self, pattern: Robj, value: Robj, literal: Robj) -> Result<Expr, String> {
        Ok(self
            .0
            .clone()
            .str()
            .replace(
                robj_to!(Expr, pattern)?.0,
                robj_to!(Expr, value)?.0,
                robj_to!(bool, literal)?,
            )
            .into())
    }

```

pattern and value could be anything which can be conveted into an Expr. wrap_e_result try to wrap any R object and pass the outcome or error to robj_to! on rust side. This gives a really nice context to the errors, which py-polars does not have.


```R
> pl$lit("hello")$str$replace("hello",Complex(5))$to_r()
Error: in str$replace: the arg [value] not convertable into Expr because:
unable to find an inherited method for function ‘Complex’ for signature ‘"numeric"’
when calling :
pl$lit("hello")$str$replace("hello", Complex(5))
```

**Comment by sorhawell** [comment]
> Does R-polars support returning ChunkedArray objects, as in the is_unique() method? I tried various simple things without success

which is_unique?

is there a py-polars returning a ChunkedArray? The polars chunkedArray is from the top of my head [only exposed in rust-polars](https://pola-rs.github.io/polars/polars/chunked_array/struct.ChunkedArray.html). It is a generic struct containing type T. The Series is basically a thin dynamic wrapper on top, much like polymorphism in C++. I cannot think of a use case where it would be beneficial in R or Python lang, to access directly the ChunkedArray.

**Comment by sorhawell** [comment]
good questions :) !

**Comment by vincentarelbundock** [comment]
Thanks for the info! If I manage to digest this in the next few days, I might open a new PR with a few more translations.

> which is_unique?

I was looking at these two methods, which are said to return "a mask":

https://pola-rs.github.io/polars/py-polars/html/reference/dataframe/api/polars.DataFrame.is_duplicated.html

https://pola-rs.github.io/polars/py-polars/html/reference/dataframe/api/polars.DataFrame.is_unique.html

The use-case I had in mind was identifying duplicated or unique rows without removing them.

**Comment by vincentarelbundock** [comment]
```rust
     --> src/rdataframe/mod.rs:88:9
      |
   87 |     fn is_duplicated(&self) -> Result<Series, String> {
      |                                ---------------------- expected `std::result::Result<series::Series, std::string::String>` because of return type
   88 |         self.0.is_unique()
      |         ^^^^^^^^^^^^^^^^^^ expected `Result<Series, String>`, found `Result<ChunkedArray<...>, ...>`
```

**Comment by sorhawell** [comment]
In the case of is_unique for DataFrame I look up how [py-polars has made the binding](https://github.com/pola-rs/polars/blob/c361d877fc7bbd275c804646ddbe471d0b991d7d/py-polars/src/dataframe.rs#L1017)

```rust
pub fn is_unique(&self) -> PyResult<PySeries> {
  let mask = self.df.is_unique().map_err(PyPolarsErr::from)?;
  Ok(mask.into_series().into())
}
```
translation to r-polars will look like this. Here I break into one extra line to let Rust-analyzer help explain the types.
```rust
pub fn is_unique(&self) -> Result<Series, String> {
    use polars::prelude::IntoSeries; // needed for .into_series(), this could move to top of file
    let mask = self.0.is_unique().map_err(|err| err.to_string())?;
    let s = mask.into_series().into();
    Ok(s)
}
```

<img width="783" alt="image" src="https://user-images.githubusercontent.com/8015271/232601347-850fc910-9d9d-4b70-998e-aa6203fbf400.png">

a rust-polars method can return a ChunkedArray, in this case `ChunkedArray<BooleanType>` we do  return a "ca"(abbreviated) to either python or R but always call `.into_series()`. This conversion need the trait `polars::prelude::IntoSeries` in scope. Sometimes it can be confusing what trait is missing. Many times the compiler error message will suggest to include this trait.
<img width="819" alt="image" src="https://user-images.githubusercontent.com/8015271/232601973-20237120-bed5-4a81-a031-98ba6f3515f9.png">

In worst cast and that can be difficult to realize, the trait is implemented via a feature flag, and before adding the feature flag to `Cargo.toml`, nothing works. The compiler cannot help with feature flags. There mentioned in rust-polars docs.

**Comment by vincentarelbundock** [comment]
Thanks a lot. I'll give this a try, but `is_duplicated()` and `is_unique()` might be lower priority use-cases anyway...

Closing this now in favor of Draft PR https://github.com/pola-rs/r-polars/pull/121
