### ISSUE TITLE
`$to_data_frame()` errors when column has datatype `Null`

### ISSUE THREAD

**Issue by etiennebacher** [pola-rs/r-polars#1216]
``` r
library(polars)
options(polars.do_not_repeat_call = TRUE)

dat = pl$DataFrame(x = NULL)
dat 
#> shape: (1, 1)
#> ┌──────┐
#> │ x    │
#> │ ---  │
#> │ null │
#> ╞══════╡
#> │ null │
#> └──────┘
dat$to_list()
#> $x
#> NULL
dat$to_data_frame()
#> Error in class(x) <- unique.default(c("AsIs", oldClass(x))): attempt to set an attribute on NULL
```

**Comment by eitsupi** [comment]
I don't know if `pl$DataFrame(x = NULL)` should generate a DataFrame of height 1 to begin with.

``` r
length(NULL)
#> [1] 0
```

``` r
arrow::arrow_table(x = NULL)
#> Table
#> 0 rows x 1 columns
#> $x <null>
```

<sup>Created on 2024-09-02 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

In my opinion, since NULL is zero length, it makes more sense to generate a DataFrame with zero height like `arrow::arrow_table()` does.

(On `next` branch, this pattern generates a DataFrame with height 0.)

``` r
neopolars::pl$DataFrame(x = NULL)
#> shape: (0, 1)
#> ┌──────┐
#> │ x    │
#> │ ---  │
#> │ null │
#> ╞══════╡
#> └──────┘
```

<sup>Created on 2024-09-02 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
