### ISSUE TITLE
support join_asof

### ISSUE THREAD

**Issue by rdavis120** [pola-rs/r-polars#151]
I'm trying to benchmark rpolars (r package) vs. other implementations of 'asof' time series joins using the R package as opposed to through reticulate - as presented by @bwlewis

https://bwlewis.github.io/duckdb_and_r/asof/asof.html

However I do not see the join_asof function exposed for DataFrame. Is this planned in the future?  Thanks!

**Comment by sorhawell** [comment]
@rdavis120   Hi rdavis120 welcome!

I have not gotten to do much benchmarking yet. I'm very curious to the results. If encountering any degraded performance compared to e.g. py-polars, we will immediately look in to that.

I will try to implement `join_asof` today.

**Comment by sorhawell** [comment]
it seems the linker extendr / r-polars uses has been moved in the Rtools4.3 bundle breaking our windows builds. The join_asof will be delayed for next week, sorry.

**Comment by sorhawell** [comment]
Hi @rdavis120 finally join_asof has been added. The [docs](https://rpolars.github.io/reference/LazyFrame_join_asof/) and is available from polars 0.6.0.

fun fact: Currently the github binary release also has SIMD-optimizations. These are currently not possible on R-universe nor in the future CRAN, because simd requires a rust-nightly. Not sure for which queries SIMD matters the most.
