### ISSUE TITLE
gotta have `sink_parquet`for streaming data

### ISSUE THREAD

**Issue by sorhawell** [pola-rs/r-polars#260]
watching this [polars talk from PyCon Italia23](https://www.youtube.com/live/s4vsucVSsL8?feature=share&t=20000) and realize we are missing sink_parquet to allow streaming data to a file

**Comment by eitsupi** [comment]
Streaming would be really great. The use of, for example, converting a huge CSV file to Parquet is all over the world.

DuckDB is unlikely to have such an API due to its purpose, and I don't think Acero currently has such a feature. Therefore, when converting a large csv to Parquet in R, I think that for now the individual must manually set the read size and repeat the process.

**Comment by etiennebacher** [comment]
I guess this can closed now: https://rpolars.github.io/reference/LazyFrame_sink_parquet/
