### ISSUE TITLE
Pin R-universe to the latest release

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/r-polars#420]
R-universe has the ability to refer to the latest release.
<https://ropensci.org/blog/2023/08/01/r-universe-and-cran/#dev-cran>

@sorhawell @etiennebacher
What do you think about stopping the current HEAD tracking and pinning the R-universe to releases after #408 is implemented?
If we implement #408 and also make the R-universe builders perform "source + pre-built binary installation" (https://github.com/pola-rs/r-polars/issues/408#issuecomment-1752288775), I believe that `Sys.setenv(NOT_CRAN = "true"); install.packages("polars", repos = "https://rpolars.r-universe.dev/")` will allow we to perform a SIMD-enabled installation on all platforms in few seconds.

The downside is that we lose the HEAD tracking binary installations.

**Comment by etiennebacher** [comment]
I like being able to get the latest features / bug fixes in a few seconds with the R-universe binaries, it can be tedious to set up a dev environment in some setups. I didn't really follow the discussion in #408, why is it necessary to pin R-universe to specific releases?

**Comment by sorhawell** [comment]
@eitsupi 

overall I think it makes sense to upgrade the R-universe to support all features. It sounds attractive.

Some quick questions:

1 - Will the plain Github releases continue as for now?
2 - Do we still tag r-polars  release versions as we normally do?
3 - I'm a little unsure on the exact way R-universe will match the correct source code with correct pre-built rust-binary. Will it also just download the source code from the release?
4 - Does that means R-universe will serve the r-polars version which is defined as latest release in github -releases? And all binaries will placed in the releases?. So instead of manually pinning R-universe, it is now done automatically to what we intended anyways? - sounds pretty fine
5 - Does binaries need to be built for every commit pushed to main?

**Comment by sorhawell** [comment]
you got me convinced, it could be very elegant :)

**Comment by eitsupi** [comment]
Thank you both, I'll be working on this in the next few days (or few weeks).
It should basically just be porting a few files over from prqlr, but I think the Makevars and documentation will need a major rewrite.

**Comment by eitsupi** [comment]
It works.

```r
r$> install.packages("polars", repos = "https://rpolars.r-universe.dev/bin/linux/jammy/4.3")
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://rpolars.r-universe.dev/bin/linux/jammy/4.3/src/contrib/polars_0.8.1.9000.tar.gz'
Content type 'application/x-gzip' length 17247103 bytes (16.4 MB)
==================================================
downloaded 16.4 MB

* installing *binary* package ‘polars’ ...
* DONE (polars)

The downloaded source packages are in
        ‘/tmp/RtmpVH4wdn/downloaded_packages’

r$> library(polars)

r$> pl$polars_info()
r-polars package version : 0.8.1.9000
rust-polars crate version: 0.33.2

Features:                         
default              TRUE
full_features        TRUE
simd                 TRUE
rpolars_debug_print FALSE
```
