### ISSUE TITLE
Rust cache does not seem working on Windows

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/r-polars#431]
I was wondering about the long build times on Windows, and it probably has something to do with symlinks not working on Windows.

https://github.com/pola-rs/r-polars/blob/2fc7ff5e5294f9f4fc9d9b8c3ee8a0254476e4cf/src/Makevars.win#L47-L52

**Comment by eitsupi** [comment]
@sorhawell I don't understand what this process is actually doing, is it creating a simlink to reference the binary in a temporary directory from within the Git repository?

**Comment by sorhawell** [comment]
R CMD check copies the source folder to a new temp, but not e.g. rust target. It will then test if the package will compile and install. This is slow problem as it has to recompile polars mostly from scratch.

`$(rpolars_ext_binary)` can be used to point back to where there already exists a rust target. If such, via a symlink
that target is "imported" into the temp R CMD check folder. Any updates to the target folder state will also propagate back to the orignal place via symlink.

It speeds up a local check from 22min to ~3 min on my machine when using [check_polars()-function](https://github.com/pola-rs/r-polars/blob/f8d6ce4ec53f7d734f1db7c6309c178048d97963/inst/misc/develop_polars.R#L80)

[It is also used to symlink rust target, between git checkout folder and R CMD check copied folder in the github action](https://github.com/pola-rs/r-polars/blob/f8d6ce4ec53f7d734f1db7c6309c178048d97963/.github/workflows/check.yaml#L84). The intention was to allow R CMD check to use the cache.

**Comment by eitsupi** [comment]
Thanks for explaining. Anyway, this doesn't seem to work on Windows, so I think it needs to be rewritten.

**Comment by eitsupi** [comment]
> `$(rpolars_ext_binary)` can be used to point back to where there already exists a rust target folder. If such, via a symlink
> that target is "imported" into the temp R CMD check folder. Any updates to the target folder state will also propagate back to the orignal place via the symlink.

Why can we shorten the build time even though they create a symbolic link after running `cargo build`?

**Comment by sorhawell** [comment]
I imagine this chain of events: 
 
 - check workflow starts
 - [checkout git](https://github.com/pola-rs/r-polars/blob/483d92c5e969ff3c53ce15d9a63e888d34891749/.github/workflows/check.yaml#L42)
 -  runs [.github/actions/setup/action.yaml](https://github.com/pola-rs/r-polars/blob/483d92c5e969ff3c53ce15d9a63e888d34891749/.github/workflows/check.yaml#L54) which via  Swatinem/rust-cache@v2  loads cache of  ./src/rust as function of cache key.
 - r cmd check creates some temp dir e.g.  at ../check/ or whereever R CMD check chooses. It does not copy the pre-compiled object files and what not from ./src/rust/
 - makevars is called during R cmd check to install the package from e.g. ../check/src/makevars
 - a symlink is created between  ./src/rust/ and ../check/src/rust/. . Therefore cargo build does not have to compile everything from scratch.
 - Only minor changes during compilation has to be recompiled, in the case of `lto='fat'` it appears some of the compilation can be reused but it still requires a slower linking phase. In best cache case the compilation takes ~20 seconds and in the worst ~30 minutes.
 - R CMD Check continues testing. Maybe ../check/ is deleted, maybe not.
 - swatinem/rust-cache@v2 will save ./src/rust/t if the cache-key is not yet defined


 > Why can we shorten the build time even though they create a symbolic link after running cargo build?
 
I think if disabling symlink in makevars, the immediate consequence would be that every check cannot utilize caching because, the check folder has just been created and target folder is copied over. Also after a full compilation the rust-cache could in theory preserve the check folder, but it would be deleted by R CMD check in next run when overwritten by a new copied folder.
 
In essence R CMD check copies to avoid statefullness between runs such as caching, and we trick R CMD check with a symlink.

The same principle for speeding local R CMD check, but just without Swatinem/rust-cache@v2.

Maybe I have missed something. I thought sometimes I understood why it is not working on Windows machine, but never really figured it out.

Feel free to try something new out :)  It will be very apparent if it is fast or not. I pray to keep the option of symlinking local checks (or any other mechanism where check does not require building from scratch) and also avoid any risk of makevars deletes previous builds as a default.

**Comment by eitsupi** [comment]
Thanks.
Anyway I succeeded in speeding up the build using the cache in the `prqlr` repository.

My understanding is that R CMD check will do clean installs of R package in two different temporary directories, so it will build the Rust library twice unless there is some ingenuity.
However, we can reduce the build to one time by building the Rust library in the Git repository in advance and setting it to use the built library.
We can also use caching in a Git repository. Unlike SimLink, it doesn't work on Windows.

**Comment by eitsupi** [comment]
Sorry, but it was a misunderstanding that the cache is not working on Windows, the results of the run after merging #435, even with the cache working, the R CMD check took about 25 minutes on Windows, not faster than before.
