### ISSUE TITLE
Release 0.9.0?

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/r-polars#441]
@sorhawell @etiennebacher A new version of rust-polars has been released, so I'm wondering if they'll release 0.9.0 before incorporating it.

I wanted to complete #435 before the 0.9.0 release, but it will probably be completed after Sunday, so I think it's okay to do it after 0.9.0.

**Comment by etiennebacher** [comment]
We released 0.8.1 about 1 month ago. Upgrading rust-polars to 0.34.2 will probably take 2-3 weeks (same as for 0.33) so I think it terms of timing we can upgrade rust-polars again and then release 0.9.0. This would also give you time to finish #435. Also, the binaries are always available via R-universe so there's no rush to release 0.9.0. 

Is there an advantage in releasing 0.9.0 now rather than in a few weeks?

**Comment by eitsupi** [comment]
I just thought it might be common practice to create a release that corresponds to an upstream release, not that I want to release it right away.

**Comment by sorhawell** [comment]
I have gotten the seasonal flu and and a larger contract to fulfill. So I will be rather slow. I will prioritize, if we're hitting any blockers in rust code.

**Comment by eitsupi** [comment]
Done in #453.

I released 0.9.0 soon because the rust-polars update changes MSRV.
If we do a CRAN release in the coming months, we may use a branch that forks from this release...
