### ISSUE TITLE
replace argname 'reverse' with 'descending'

### ISSUE THREAD

**Issue by sorhawell** [pola-rs/r-polars#51]
In [this PR ](https://github.com/pola-rs/polars/commit/c7b85997aa6e25746104a2f56ced177a37b2f132 ) py-polars deprecated 'reverse'  over 'descending'

r-polars should follow along in all parallel functions

**Comment by bugslayer-332** [comment]
Hi @sorhawell, I am Arepalli Yashwanth Reddy a Third year Undergrad at IIT Kharagpur pursuing my Bachelor of Technology in Industrial Engineering dealing with Data science problems very frequently and have been using R since a year. I also started learning rust in my previous Winter break and am very interested in this project. I have been exploring the code-base.
Can I work on this issue ?

**Comment by bugslayer-332** [comment]
@sorhawell I am getting certain doubts while working with this. Should I post it here itself or is there a slack channel where I can have this conversation.

**Comment by sorhawell** [comment]
Good question r-polars has [a channel called "r-polars" on polars discord](https://discord.com/channels/908022250106667068/1057287033778876566) which we can use. If this link works well, I will add it to the top of readme.md

**Comment by bugslayer-332** [comment]
Actually this link didn't direct me to the channel. I joined via the polars discord server link from their official page.
