### ISSUE TITLE
plot methods?

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/r-polars#699]
I am wondering if it is worth adding S3 methods regarding base plot and `ggplot2` etc.
(Probably not worth doing as in most cases it would just be converting to data.frame and then calling the method for data.frame so there would be no performance benefit at all, but I can't say for sure as I am not familiar with plots)

**Comment by etiennebacher** [comment]
They added `plot` methods in the python API because some Python plotting libraries have been working on taking a polars DataFrame as input directly. I don't think there would be perf benefits here since any plotting package or method would have to convert to a standard data.frame under the hood. Basically, I don't think it's worth implementing here when using `$to_data_frame()` gives something that can be manipulated with `plot()` / `ggplot2`.
