### ISSUE TITLE
Set options via the `options` function

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/r-polars#713]
Perhaps something like `pl$set_options` should work as a shortcut for the options function.

**Comment by etiennebacher** [comment]
For options and envvars, maybe it would indeed make more sense to diverge from polars since R users are used to `options()`, `Sys.setenv()`, and the `withr` functions for advanced users.

What I really dislike about `options()` and `Sys.setenv()` is that I find it hard to easily get a list of options / envvars available for a package. If we add support for those, we should make sure those are easy to find. One way would be to add `polars_options()` and `polars_envvars()` that would complement `polars_info()`. Those would just print a list of envvars/options with their description (like `polars_info()`).

In this case maybe it wouldn't make sense to keep `pl$set_options()` and `pl$options` in the long run, and those could be deprecated
---

Note: polars envvars: https://github.com/pola-rs/polars/blob/62ecdd3e14e485baa84750b92a6615bc8d680b54/py-polars/polars/config.py#L45
