### ISSUE TITLE
Should charactor be treated as column names in some functions like Python Polars?

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/r-polars#715]
I learned that Python Polars now treats strings as column names within when-then (See pola-rs/polars#13611).
Should we imitate something like this? Or should it be evaluated by NSE?

From a consistency point of view, functions such as `pl$select`, as listed in the README, currently interpret strings as column names.

https://github.com/pola-rs/r-polars/blob/7c842ada45112b320eac0245bd9aa56fbc2fd7d2/README.md?plain=1#L76-L85

Since I think NSE is generally used better in the R world, I would personally remove this behavior from the R package and enforce column specification by `pl$col()`.
(We could consider introducing NSE, but in that case it would be better to add the `rlang` package as a dependency.)

So my opinion is:

- charactor within when-then should not be treated as column names.
- It may be worth removing the behavior of treating strings as column names from within all functions.
- It may be worthwhile to add the ability to specify column names by NSE within the function Python Polars uses to treat strings as column names.

@sorhawell @etiennebacher Thoughts?

Related past discussion #532

**Comment by etiennebacher** [comment]
Well at first glance I disagree with all your suggestions 😄 

The main thing for me is that I don't want to diverge from the py-polars API, and I think we should stick to it as much as possible. Overall, I really like the one-to-one matching between py-polars and r-polars. It makes debugging much easier: my r-polars code doesn't work, or panics, or whatever? One of the most important steps is to check the behavior in py-polars to see if it's from our implementation or from upstream. Removing some functionalities that are so widely used in py-polars would make the translation much more annoying to make. I can also imagine that the reverse is true: people see examples in py-polars and want to run them in R, copy-paste the example, and it doesn't work. That would be very frustrating.

I think the current polars landscape in R is going in the right direction:

- `polars` for people who want to get the exact translation of the python API
- `polarssql` for people who want SQL syntax
- `tidypolars` for people who want tidy syntax

It is also worth nothing that selecting columns with strings also creates some confusion in py-polars (https://github.com/pola-rs/polars/issues/13805) so there *might* be some changes soon.

I'm also curious to know what others think about this. @vincentarelbundock @grantmcdermott I don't know if you currently use r-polars but if so, do you have an opinion on this?

**Comment by vincentarelbundock** [comment]
I don't use it enough to have a strong view, but agree in general that consistency with Python is one of the big benefits.

Also, not a big fan of NSE in R when we can avoid it.

**Comment by grantmcdermott** [comment]
> I think the current polars landscape in R is going in the right direction:
> - polars for people who want to get the exact translation of the python API
> - polarssql for people who want SQL syntax
> - tidypolars for people who want tidy syntax

+1 to this. (I would only add that polarsql could be an alternative intermediary to tidy syntax via dbplyr, but that's splitting hairs.)

To my mind, maintaining API/syntax equivalency between the "base" Python and R polars frontends should be a primary goal of this project. It's one of the biggest selling points when I've been giving workshops on polars to polyglot teams at Amazon.

**Comment by sorhawell** [comment]
Interesting move from py-polars. Maybe the syntax becomes more effortless to write.

I guess it is question of perspective. I do not thinkg of it as an NSE issue, but just question of how to define conversions of R parameters to rust-polars.

An advantage of the `robj_to!`-macro is that we have a centralized definitions of converting any input parameters.

Today any methods that takes an Expr as input, will happily also take a string (or charvec) and convert it to a literal-Expr.
Many py-polars r-polars function will instead convert to a col-Expr e.g. select. Before py-polars favored the either literal or col for what would be expected most used for any method. I guess they changed philosophy, to "always col-Expr, because easier to remember that way, and col-Expr is overall most used".

We express over preference with  `robj_to!(Expr, ...)`. vs `robj_to!(ExprCol, ...)`

I would probably recommend to blindly search replace all use of  `robj_to!(Expr, ...` with  `robj_to!(ExprCol` and `robj_to!(PLExpr,` with `robj_to!(PLExprCol` and something similar for the keywords `VecPLExpr` + `VecPLExprNamed`.

[or in theory if being very lazy just swap around these lines, but that would be silly](https://github.com/pola-rs/r-polars/blob/7c842ada45112b320eac0245bd9aa56fbc2fd7d2/src/rust/src/utils/mod.rs#L978C1-L992C7).

I'm sure a lot of unit test would need some updates, because this would biggest breaking change to date.
There are still old school conversions which needs an update to robj_to!


digging deeper into the current definition of  macro call `let my_rust_arg = robj_to!(ExprCol, my_r_arg)?`

[pattern matches this line in the macro rules](https://github.com/pola-rs/r-polars/blob/7c842ada45112b320eac0245bd9aa56fbc2fd7d2/src/rust/src/utils/mod.rs#L979)

which finally calls
```rust
use crate::lazy::dsl::Expr;
use crate::robj_to;
use crate::rpolarserr::*;
use extendr_api::prelude::*;

#[extendr]
pub fn robj_to_col(name: Robj) -> RResult<RPolarsExpr> {
    let vs: Vec<String> = robj_to!(Vec, String, name)?;
    Ok(Expr::cols(vs))
}
```

**Comment by eitsupi** [comment]
Thanks everyone for the replies.

> The main thing for me is that I don't want to diverge from the py-polars API, and I think we should stick to it as much as possible.

@etiennebacher I am surprised that you have such an opinion, as I interpreted it to mean that you were opposed to introducing a syntax equivalent to the Python API in #532.

**Comment by eitsupi** [comment]
Example of interpreting a string as a column name, which looks quite unnatural:

``` r
library(polars)

df <- pl$DataFrame(
  foo = 1:2,
  bar = 3:4,
  baz = 5:6
)

foo <- "bar"

df$select(
  1,
  paste0("fo", "o"),
  foo,
  baz = foo
)
#> shape: (2, 4)
#> ┌─────────┬─────┬─────┬─────┐
#> │ literal ┆ foo ┆ bar ┆ baz │
#> │ ---     ┆ --- ┆ --- ┆ --- │
#> │ f64     ┆ i32 ┆ i32 ┆ i32 │
#> ╞═════════╪═════╪═════╪═════╡
#> │ 1.0     ┆ 1   ┆ 3   ┆ 3   │
#> │ 1.0     ┆ 2   ┆ 4   ┆ 4   │
#> └─────────┴─────┴─────┴─────┘
```

<sup>Created on 2024-01-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by eitsupi** [comment]
This actually seems to be consistent with the upstream Rust Polars rule, so closing.
